apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
spec:
  containers:
  - image: docker.io/nvidia/cuda:11.2.1-base
    name: nvidia-smi
    command: ["/bin/bash", "-c","nvidia-smi; exit 0" ]
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        nvidia.com/gpu: 1
    env:
    - name: http_proxy
      value: http://oji01webcache01.apj.hpecore.net:8080
    - name: https_proxy
      value: http://oji01webcache01.apj.hpecore.net:8080
  tolerations:
  - key: "nodetype"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
  restartPolicy: Never
