apiVersion: v1
kind: Pod
metadata:
  name: entitled-build-pod
spec:
  containers:
    - name: entitled-build
      image: registry.access.redhat.com/ubi8:latest 
      command: [ "/bin/sh", "-c", "dnf search kernel-devel --showduplicates" ]
      env:
      - name: http_proxy
        value: http://oji01webcache01.apj.hpecore.net:8080
      - name: https_proxy
        value: http://oji01webcache01.apj.hpecore.net:8080
      volumeMounts:
          - name: secret-entitlement
            mountPath: /etc/pki/entitlement
            readOnly: true
  volumes:
    - name: secret-entitlement
      secret:
        secretName: entitlement
  restartPolicy: Never
