apiVersion: v1
kind: Pod
metadata:
  name: cluster-entitled-build-pod
spec:
  containers:
    - name: cluster-entitled-build
      image: registry.access.redhat.com/ubi8:latest 
      command: [ "/bin/sh", "-c", "dnf search kernel-devel --showduplicates" ]
      # restartPolicy: Never
      env:
      - name: http_proxy
        value: http://oji01webcache01.apj.hpecore.net:8080
      - name: https_proxy
        value: http://oji01webcache01.apj.hpecore.net:8080
  restartPolicy: Never
